export const categories = [
  { title: "Todos", path: "/" },
  { title: "Aceite", path: "/Category/Aceite" },
  { title: "Alfajor", path: "/Category/Alfajor" },
  { title: "Arroz", path: "/Category/Arroz" },
  { title: "Avena", path: "/Category/Avena" },
  { title: "Azucar", path: "/Category/Azucar" },
  { title: "Barritas", path: "/Category/Barritas" },
  { title: "Brownie", path: "/Category/Brownie" },
  { title: "Cereal", path: "/Category/Cereal" },
  { title: "Chocolate", path: "/Category/Chocolate" },
  { title: "Condimento", path: "/Category/Condimento" },
  { title: "Dulce de leche", path: "/Category/Dulce de leche" },
  { title: "Fideos", path: "/Category/Fideos" },
  { title: "Fruto secos", path: "/Category/Fruto secos" },
  { title: "Galletas", path: "/Category/Galletas" },
  { title: "Granola", path: "/Category/Granola" },
  { title: "Harina", path: "/Category/Harina" },
  { title: "Heladera", path: "/Category/Heladera" },
  { title: "Leche", path: "/Category/Leche" },
  { title: "Mermeladas", path: "/Category/Mermeladas" },
  { title: "Nutrileva", path: "/Category/nutrileva" },
  { title: "Pan", path: "/Category/pan" },
  { title: "Pasta de mani", path: "/Category/Pasta-de-mani" },
  { title: "Porotos", path: "/Category/Porotos" },
  { title: "Producto", path: "/Category/Producto" },
  { title: "Sal", path: "/Category/Sal" },
  { title: "Semillas", path: "/Category/Semillas" },
  { title: "Soja", path: "/Category/Soja" },
  { title: "Stevia", path: "/Category/Stevia" },
  { title: "Te", path: "/Category/Te" },
  { title: "Vainillas", path: "/Category/Vainillas" },
  { title: "Yerba", path: "/Category/Yerba" },
  { title: "Yuyo", path: "/Category/Yuyo" },
];
