export const categories = [
  { title: "Todos", path: "/" },
  { title: "Aceite", path: "/Category/aceite" },
  { title: "Alfajor", path: "/Category/alfajor" },
  { title: "Arroz", path: "/Category/arroz" },
  { title: "Avena", path: "/Category/avena" },
  { title: "Azucar", path: "/Category/azucar" },
  { title: "Barritas", path: "/Category/barritas" },
  { title: "Brownie", path: "/Category/brownie" },
  { title: "Cereal", path: "/Category/cereal" },
  { title: "Chocolate", path: "/Category/chocolate" },
  { title: "Condimento", path: "/Category/condimento" },
  { title: "Dulce de leche", path: "/Category/dulce-de-leche" },
  { title: "Fideos", path: "/Category/fideos" },
  { title: "Frutos secos", path: "/Category/frutos-secos" },
  { title: "Galletas", path: "/Category/galletas" },
  { title: "Granola", path: "/Category/granola" },
  { title: "Harina", path: "/Category/harina" },
  { title: "Heladera", path: "/Category/heladera" },
  { title: "Leche", path: "/Category/leche" },
  { title: "Mermeladas", path: "/Category/mermeladas" },
  { title: "Nutrileva", path: "/Category/nutrileva" },
  { title: "Pan", path: "/Category/pan" },
  { title: "Pasta de mani", path: "/Category/pasta-de-mani" },
  { title: "Porotos", path: "/Category/porotos" },
  { title: "Producto", path: "/Category/producto" },
  { title: "Sal", path: "/Category/sal" },
  { title: "Semillas", path: "/Category/semillas" },
  { title: "Soja", path: "/Category/soja" },
  { title: "Stevia", path: "/Category/stevia" },
  { title: "Te", path: "/Category/te" },
  { title: "Vainillas", path: "/Category/vainillas" },
  { title: "Yerba", path: "/Category/yerba" },
  { title: "Yuyo", path: "/Category/yuyo" },
];
